# Generated by Django 4.0.3 on 2022-04-11 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='registered_users',
            field=models.ManyToManyField(blank=True, help_text='users who are invited to the group', related_name='registered_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
